### ISSUE TITLE
裁剪不能按照固定宽高尺寸截取么？

### ISSUE THREAD

**Issue by pxim** [sinashahoveisi/antd-cropper-img#2]
裁剪不能按照固定宽高尺寸截取么？

**Comment by srqAndwr** [comment]
+1，求解答

**Comment by sinashahoveisi** [comment]
@pxim 

Yes, you can set the initial crop in version `1.0.3` and later like this:

`<CropperImage initialCrop={{width: 50, height: 50}} cropBoxResizable={false}>`
