### ISSUE TITLE
No way to change increase zoom amount

### ISSUE THREAD

**Issue by Joshuajrodrigues** [sinashahoveisi/antd-cropper-img#4]
**Is your feature request related to a problem? Please describe.**
Need a prop similar to [wheelZoomRatio](https://www.npmjs.com/package/antd-cropper-img#wheelzoomratio) for zoom on slider button as the default 1 is too much in source

**Describe the solution you'd like**
prop similar to [wheelZoomRatio](https://www.npmjs.com/package/antd-cropper-img#wheelzoomratio)

**Describe alternatives you've considered**

**Additional context**

**Comment by sinashahoveisi** [comment]
`zoomAmount` and `zoomStep` props add to version `1.1.0`
