### ISSUE TITLE
Allow customizing slider buttons and Ok/Cancel Button in the footer.

### ISSUE THREAD

**Issue by 2vergent** [sinashahoveisi/antd-cropper-img#6]
First of all I want to say that I'm so grateful that this package exists specifically for AntD's Upload component. I have custom Button components for an OK button and Cancel button which I would like to use instead of the default AntD buttons in the Crop Modal.

It would be so easy if there was a prop like "okButtonProps"/"cancelButtonProps "which takes "ButtonProps" for customizing the Ok/Cancel Buttons. There is also the "footer" prop in the default AntD modal using which you can customize your Modal footer content.

In the screenshot below, I could only have limited customization of the button by overriding the default CSS. I would like to have custom buttons with icons, so that I can have loading animations and goodies like that.

![image](https://github.com/sinashahoveisi/antd-cropper-img/assets/55847410/f28919b7-4bfa-40d7-b564-59652b2c925d)

The CSS I wrote: 
```
.antd-cropper-img-modal .ant-btn-primary {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 20px !important;
  height: 35px !important;
  width: 30%;
}

.antd-cropper-img-modal .ant-modal-footer {
  margin-top: 30px;
}

.antd-cropper-img-modal .ant-modal-footer .ant-btn-default {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 20px !important;
  height: 35px !important;
  width: 30%;
}

.antd-cropper-img-modal .actions-row .ant-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 20px !important;
  height: 35px !important;
  width: 10%;
}

.antd-cropper-img-modal .actions-row .ant-btn > span {
  font-size: 18px;
}
```

**Comment by sinashahoveisi** [comment]
@2vergent  Thank you for providing this package and considering feedback. The features you mentioned have been added in version `1.2.0` making it compatible with the latest Ant Design version.
